### ISSUE TITLE
ValueError: Buffer has wrong number of dimensions (expected 2, got 3)

### ISSUE THREAD

**Issue by EAlexJ** [user29A/fastrometry#4]
Hi all,
when running fastrometry on the file obtained from here: https://fits.gsfc.nasa.gov/nrao_data/samples/hst/w0bu0101t_c0h.fit.gz I get the error below. 
```
% fastrometry w0bs0102t_c0h.fit -ra "RA" -dec "DEC" -scale 0.9 
.
.
.
Extracting sources from image...
Traceback (most recent call last):
  File "/Users/alex/Astronomy/fastrometry/.venv/bin/fastrometry", line 8, in <module>
    sys.exit(callFromCommandLine())
         
  File "/Users/alex/Astronomy/fastrometry/.venv/lib/python3.11/site-packages/fastrometry/fastrometry.py", line 885, in callFromCommandLine
    solution = findWCS(args.filename, ra=args.ra, dec=args.dec, scale=args.scale, scalebnds=args.scalebnds, rotation=args.rotation, rotationbnds=args.rotationbnds, buffer=args.buffer, fieldshape=args.fieldshape, catalogue=args.catalogue, filter=args.filter, pmepoch=args.pmepoch, npts=args.npts, nrefinepts=args.nrefinepts, pixsat=args.pixsat, kernelrad=args.kernelrad, sourcesep=args.sourcesep, vertextol=args.vertextol, nmatchpoints=args.nmatchpoints, nmatchpercent=args.nmatchpercent, wcsdiagnostics=args.wcsdiagnostics, overwrite=args.overwrite, save=args.save, load=args.load, verbosity=args.verbosity, debug=args.debug)

  File "/Users/alex/Astronomy/fastrometry/.venv/lib/python3.11/site-packages/fastrometry/fastrometry.py", line 784, in findWCS
    num_psesources = PSE(img, img_xmax, img_ymax, kernelrad, sourcesep, pixsat, npts, nrefinepts, pixelradius, fieldshape, srcindexmap_initial, srcindexmap_refine, pse_metadata, debug_report, filepath, debug, verbosity)
                     
  File "PSE.pyx", line 528, in fastrometry.cython_code.PSE.PSE
ValueError: Buffer has wrong number of dimensions (expected 2, got 3)
```

**Comment by user29A** [comment]
Thanks EAlexJ.

Cameron, it might have something to do with the source image being 3D instead of just 2D? 

Not sure what "Buffer" is being referred to on that line, but "Buffer has wrong number of dimensions (expected 2, got 3)" might have something to do with the source file being 3D.

That said, EAlexJ, those images are terrible - full of noise, artefacts, and the field is only 86 arcseconds across. Why do they need to be solved? They look like junk to me, unless there's some good reason why they need a solution...

I doubt the solver would work on them in the state that they're in. Maybe if they had some pre-processing done on them to clean them up a bit?

Cheers,

Joe

**Comment by cam92473** [comment]
Hi all,

That file is in an image cube format. fastrometry doesn't currently have
the capability of accepting that type of input, but it will work on the
individual images that make up the cube (for example, one could use astropy
to save each image in the cube as a new fits image, and then one could work
with these). Even so, fastrometry is having difficulty solving these
images. I'm currently taking a look at the problem and will let you know if
I can get fastrometry to work on them.

Thanks,

Cameron

**Comment by user29A** [comment]
Yes it is a very strange file. From what I can see, the first image layer of the data corresponds to the RA & DEC listed in the header, but that layer only has two sources in it, and a WCS requires at least 3 sources to make a solution. The other 3 layers are from somewhere else, and they also have only 1 or 2 sources in them, and regardless without an approximate RA & DEC it is a blind problem.

I don't think these images can really be solved at all.

**Comment by cam92473** [comment]
Yes, other than the first image, the world coordinates don't seem to be
very accurate. By looking in Simbad I think I found the true coordinates of
the third image, but even when I pointed fastrometry there it still didn't
give a solution. To reiterate what Joe mentioned, the images are too small
and the quality is too poor. If there are very few sources and the image is
filled with artefacts and speckling, fastrometry will not produce a good
source map. Then, with such a small image, there is not much chance of
finding sources in online catalogues that correspond to anything in the
faulty source map.

Cameron

**Comment by EAlexJ** [comment]
Hi Joe, Hi Cameron,
I am fairly new to astrometry and am trying to find alternatives to a current pipeline relying on IRAF. Since I am at the stage of playing around I figured I test with some files off the web before trying to figure out why some off the ones im working on don't work. I see now why the file I chose is not a good fit for that purpose.
I know this is probably not the best place to ask, but could you point me in the direction of where to find observations that could serve as test cases?

Thanks a lot,
Eyck

**Comment by user29A** [comment]
Hi Eyck,

Here are a few sample images: 

https://drive.google.com/file/d/1a0Zgu9d5zx0D-v3Ay2UsTclDhQBbz-Z8/view?usp=share_link

Just use the CDELT keyword value from their headers for the scale argument, and the one image uses RA_PNT & DEC_PNT instead of just RA & DEC. If you're writing your own script in Python or if you're using Linux then fastrometry should work great. If you can write on other platforms you can try the implementation in JPFITS which is in C#:

https://github.com/user29A/JPFITS/releases/tag/2023.02.25

CCDLAB for Windows also lets you solve in batches, or one at a time:

https://github.com/user29A/CCDLAB/releases/tag/2023.02.16

Hope that helps!

Joe
